//HintName: ProxyGeneratorAttributes.g.cs
// <auto-generated />

#nullable enable

namespace MicroCs.Generators.Aop
{   // OK
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    internal sealed class GenerateProxyAttribute : global::System.Attribute
    {
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
    internal sealed class InterceptorAttribute : global::System.Attribute
    {
    }
}
