//HintName: LoggingProxyGeneratorClass.0.g.cs
// <auto-generated />

#nullable enable

namespace Sample.BeforeCall;

partial class LoggingProxyGeneratorClass
{
    private static readonly global::System.Type ProxyType_Cache = typeof(LoggingProxyGeneratorClass);

    public LoggingProxyGeneratorClass(
        global::Sample.BeforeCall.IProxyGeneratorInterface iproxygeneratorinterface,
        global::Sample.BeforeCall.LoggingInterceptors interceptors)
    {
        this.iproxygeneratorinterface = iproxygeneratorinterface;
        this.interceptors = interceptors;
    }

    #region [ IProxyGeneratorInterface ]

    private readonly global::Sample.BeforeCall.IProxyGeneratorInterface iproxygeneratorinterface;

    private static readonly global::System.Type IProxyGeneratorInterface_TargetType_Cache = typeof(global::Sample.BeforeCall.IProxyGeneratorInterface);

    #endregion [ IProxyGeneratorInterface ]
}
