//HintName: ProxyGeneratorAttributes.g.cs
// <auto-generated />

#nullable enable

namespace MicroCs.Generators.Aop
{   // OK
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    internal sealed class GenerateProxyAttribute : System.Attribute
    {
    }

    [System.AttributeUsage(System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
    internal sealed class InterceptorAttribute : System.Attribute
    {
    }
}
