//HintName: ProxyGeneratorAttributes.g.cs
// <auto-generated />
#nullable enable
namespace MicroCs.Generators.Aop;
[System.AttributeUsageAttribute(System.AttributeTargets.Class)]
internal sealed class GenerateProxyAttribute : System.Attribute
{
}

[System.AttributeUsageAttribute(System.AttributeTargets.Field)]
internal sealed class InterceptorAttribute : System.Attribute
{
}