//HintName: LoggingProxyGeneratorClass.0.g.cs
// <auto-generated />
#nullable enable
namespace MicroCs.Generators.Samples.NoInterceptionAttributes;
partial class LoggingProxyGeneratorClass
{
    public LoggingProxyGeneratorClass(global::MicroCs.Generators.Lib.Samples.NoInterceptionAttributes.IProxyGeneratorInterface iProxyGeneratorInterface, global::MicroCs.Generators.Lib.Samples.NoInterceptionAttributes.LoggingInterceptors interceptors)
    {
        this.iProxyGeneratorInterface = iProxyGeneratorInterface;
        this.interceptors = interceptors;
    }

    static LoggingProxyGeneratorClass()
    {
    }

    private readonly global::MicroCs.Generators.Lib.Samples.NoInterceptionAttributes.IProxyGeneratorInterface iProxyGeneratorInterface;
    void global::MicroCs.Generators.Lib.Samples.NoInterceptionAttributes.IProxyGeneratorInterface.MyMethod()
    {
        iProxyGeneratorInterface.MyMethod();
    }
}