// <auto-generated />

#nullable enable

{{~ if HasNamespace ~}}
namespace {{Namespace}};
{{~ end ~}}

partial class {{Name}}
{
    private static readonly global::System.Type ProxyType_Cache = typeof({{Name}});

    public {{Name}}(
        {{~ for itf in Interfaces ~}}
        {{itf.InterfaceType.FullName}} {{itf.ParameterName}},
        {{~ end ~}}
        {{Interceptor.InterceptorType.FullName}} {{Interceptor.ParameterName}})
    {
        {{~ for itf in Interfaces ~}}
        this.{{itf.ParameterName}} = {{itf.ParameterName}};
        {{~ end ~}}
        this.{{Interceptor.ParameterName}} = {{Interceptor.ParameterName}};
    }
    {{~ for itf in Interfaces ~}}

    #region [ {{itf.InterfaceType.Name}} ]

    private readonly {{itf.InterfaceType.FullName}} {{itf.ParameterName}};

    private static readonly global::System.Type {{itf.InterfaceType.Name}}_TargetType_Cache = typeof({{itf.InterfaceType.FullName}});

    #endregion [ {{itf.InterfaceType.Name}} ]
    {{~ end ~}}
}
